name: Build Projects
description: Reads projects from a JSON file, builds them, and uploads the resulting files.
inputs:
  json_file:
    description: 'Path to the JSON file containing project details'
    required: true
  upload_folder:
    description: 'Folder to upload the binary files'
    required: true
  bin_folder:
    description: 'Binary files folder'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true
  git_version:
    description: 'GitHub Version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Make script executable
      shell: bash
      run: |
        chmod +x ./scripts/docker_build.sh

    - name: Build and upload projects
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        ./scripts/docker_build.sh ${{ inputs.json_file }} ${{ inputs.upload_folder }} ${{ inputs.bin_folder }}

    - name: Uploading Files
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: binaries_${{ inputs.git_version }}
        path: ${{ inputs.upload_folder }}/