#
#compiler flag config domain
#

CONFIG_SYS_APP_TASK_STACK_SIZE:=2048
CONFIG_SYS_APP_TASK_PRIORITY:=15
CONFIG_CLI_CMD_ENABLE:=1
CONFIG_LOG_ENABLED_COMPONENTS:=hci_raw hci_bridge
#CONFIG_UART_STDIO_PORT:=1
#CONFIG_OPERATION_UART_PORT:=0