#
#compiler flag config domain
#

CONFIG_SYS_APP_TASK_STACK_SIZE:=4096
CONFIG_SYS_APP_TASK_PRIORITY:=15

CONFIG_LOG_ENABLED_COMPONENTS:=subg_thread_ncp rt582_hosal openthread openthread_port lmac15p4 cpc
CONFIG_CLI_CMD_ENABLE:=1

CONFIG_HOSAL_RF_DEBUG:=0

CONFIG_CPC_RX_PAYLOAD_MAX_LENGTH:=620
