#
# "main" pseudo-component makefile.
#
# (Uses default behaviour of compiling all source files in directory, adding 'include' to include path.)

ifdef CONFIG_PLATFORM_RADIO_PROPRIETARY_SUPPORT
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_SUPPORT=$(CONFIG_PLATFORM_RADIO_PROPRIETARY_SUPPORT)
endif

ifdef CONFIG_RADIO_915MHZ_OQPSK_SUPPORT
CPPFLAGS += -DOPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT=$(CONFIG_RADIO_915MHZ_OQPSK_SUPPORT)
endif

ifdef CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT
CPPFLAGS += -DOPENTHREAD_CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT=$(CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT)
endif

ifdef CONFIG_PLATOFRM_ENABLE_SLEEP
CPPFLAGS += -DCONFIG_PLATOFRM_ENABLE_SLEEP=$(CONFIG_PLATOFRM_ENABLE_SLEEP)
endif

ifeq ($(CONFIG_PLATFORM_RADIO_PROPRIETARY_SUPPORT), 1)

ifeq ($(CONFIG_SUBG_FREQUENCY_BAND), 433) #433-435(spacing 500)
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK=0x0000001f
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MIN=1
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MAX=4
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_PAGE=5
else ifeq ($(CONFIG_SUBG_FREQUENCY_BAND), 470) #470-510(spacing 2000)
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK=0x001fffff
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MIN=1
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MAX=20
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_PAGE=4
else ifeq ($(CONFIG_SUBG_FREQUENCY_BAND), 868) #863-870(spacing 500)
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK=0x00007fff
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MIN=1
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MAX=14
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_PAGE=3
else ifeq ($(CONFIG_SUBG_FREQUENCY_BAND), 915)  #920-925(spacing 500), 915 MHZ range is (902~928), but Taiwan range is (920~925)
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK=0x000007ff
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MIN=1
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MAX=10
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_PAGE=2
endif
CPPFLAGS += -DOPENTHREAD_CONFIG_DEFAULT_CHANNEL=1
endif

COMPONENT_ADD_INCLUDEDIRS += Include
